CREATE TABLE IF NOT EXISTS tracks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    file_path TEXT NOT NULL,
    cover_path TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
